### ISSUE TITLE
pzem-004t and esp8266 with compatible level 3.3v

### ISSUE THREAD

**Issue by 0neday** [TheHWcave/Peacefair-PZEM-004T-#1]
we know pzem-004t use 5v level for uart, and esp8266 ( nodeMCU ) use 3.3v level. 
I check your [PZEM004T-orig.pdf](https://github.com/TheHWcave/Peacefair-PZEM-004T-/blob/main/PZEM004T-orig.pdf), and this [discuss ](https://github.com/olehs/PZEM004T/wiki/Make-PZEM-3.3v-compatible) , this [commit ](https://github.com/olehs/PZEM004T/issues/38#issuecomment-509928046)

![捕获.PNG](https://s2.loli.net/2022/03/21/WL2FvkAQJemOrBn.png)
change `R8` to 10-100, so that when `RX `port get ` 0 level` from esp8266, so that `U3` `pin 1 ` can get enough voltage and turn on  `U3`.

**Comment by Utyff** [comment]
PZEM-004 works well from 3.3V without changing the resistor. I checked on CC2530.

**Comment by 0neday** [comment]
thank you, I will test

**Comment by 0neday** [comment]
@Utyff yes, 3.3v is work fine for pzem-004t v3.0 , maybe parallel  `R8 ` and `R10` 's resister is `500 ohm`

**Comment by rrelande** [comment]
I assume we are talking about running PZEM-004T v3 with 3v3 on UART pin instead of 5V
without modifying R8

according to theoretical calculations, it would barely work as the CT8217C optocoupler delivers a collector current of 5mA at saturation voltage. (5V 1k R7 resistor)
This would mean that the limited forward current of 2mA may not open the optocoupler to saturation. A If of 4mA would indeed secure the optocoiupler opening. 

that is theory, but is there any practical feedback?

**Comment by rrelande** [comment]
just checked on multimeter , 
using unmodified v3 and 3V3 on UART power supply to RX
the current is 3.6 mA at 25 deg - this is more than theoretical calculation. it could be enough to saturate the optocoupler

so why make hardware modifications?
