### ISSUE TITLE
Capacitors values

### ISSUE THREAD

**Issue by mercenaruss** [TheHWcave/Peacefair-PZEM-004T-#2]
Thank you for your work on this.
It's possible somehow to identify values for capacitors in this schematic?
using RLC/LCT tester [LINK](https://botland.store/other-meters/12102-transistor-and-rlc-tester-lcr-t4-5904422318628.html)

**Comment by TheHWcave** [comment]
Measuring capacitors in circuit is always very hit and miss. It depends what else is connected to the capacitors and whether that forms a path across the capacitor somehow. It also depends how it is measured, Very expensive LCR meters use AC of a selectable frequency, say 1 kHz but cheaper ones like the one you linked and all multimeters use a method where they periodically charge the cap and measure how long it takes before it reaches a certain voltage. Longer time = higher capacitance. This method works normally well but has problems one needs to be aware of. For example a very leaky capacitor will show as a cap which much higher capacitance because it takes much longer to accumulate charge which is mistakenly interpreted as a higher capacitance. So if you measure an old  electrolytic cap of say 10uF and it shows as 15 or 20uF it probably means it has too much leakage current. 

Some testers use a very low test voltage (below 0.6V) to avoid turning most diodes or transistors on. That works better in circuit but still has problems with Schottky diodes or, in a a capacitor-dropper arrangement, the discharge resistor across the cap. In short, measuring in circuit works sometimes but I would not call it a reliable. 

    On Wednesday, 31 August 2022 at 09:00:02 BST, Radu ***@***.***> wrote:  
 
 


Thank you for your work on this.
It's possible somehow to identify values for capacitors in this schematic?
using RLC/LCT tester LINK
